const experiences = [
  {
    id: "1",
    title: "Cave and Canyon Trail",
    tag: "Featured",
    imageName: "earth-1.jpg",
    desc: `Go to Las Vegas and check out the epic Canyon trails and discover some awesome hidden caves.`,
  },
  {
    id: "2",
    title: "Cross the mountains",
    tag: "Air",
    imageName: "earth-3.jpg",
    desc: `Challenge yourself physically and mentally and reach "the steps to heaven".`,
  },
  {
    id: "3",
    title: "Ride the shark waves",
    tag: "Experiences",
    imageName: "water-7.jpg",
    desc: `We'll take you to Hawaii where you can live a lifelong dream many people have - surfing among the sharks.`,
  },
  {
    id: "4",
    title: "Underwater Exploration",
    tag: "Water",
    imageName: "water-4.jpg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque voluptate quod corporis tenetur labore obcaecati eius vitae error amet illum.`,
  },
  {
    id: "5",
    title: "Tropical Getaway",
    tag: "Earth",
    imageName: "earth-6.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae autem cumque accusantium est delectus hic laboriosam odit quisquam, sapiente tempore.`,
  },
  {
    id: "11",
    title: "Rock Climbing in Yosemite, California",
    tag: "Earth",
    imageName: "earth-1.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "12",
    title: "Exploring in the Chilean Patagonia",
    tag: "Earth",
    imageName: "earth-2.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "13",
    title: "Ziplining in Costa Rica",
    tag: "Earth",
    imageName: "earth-3.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "14",
    title: "Backcountry Camping in White Sands",
    tag: "Earth",
    imageName: "earth-4.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "15",
    title: "Exploring in Hang Son Doong Cave",
    tag: "Earth",
    imageName: "earth-5.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "21",
    title: "Floating in the Dead Sea",
    tag: "Water",
    imageName: "water-1.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "22",
    title: "Surfing in Lake Tahoe, California",
    tag: "Water",
    imageName: "water-2.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "23",
    title: "Relaxing by Thor's Well, Oregon",
    tag: "Water",
    imageName: "water-3.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "24",
    title: "Underwater Exploration",
    tag: "Water",
    imageName: "water-4.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "25",
    title: "Tropical Getaway to Bigar Cascade Falls",
    tag: "Water",
    imageName: "water-5.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "31",
    title: "Northern Lights magic",
    tag: "Air",
    imageName: "air-1.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "32",
    title: "Flying over Sea Islands",
    tag: "Air",
    imageName: "air-2.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "33",
    title: "Stargazing Getaway",
    tag: "Air",
    imageName: "air-3.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "34",
    title: "Romantic isolation in Bonnell",
    tag: "Air",
    imageName: "air-4.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
  {
    id: "35",
    title: "Experiencing high winds at Big Sur",
    tag: "Air",
    imageName: "air-5.jpg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, commodi. Totam fuga sit neque vitae labore.`,
  },
]

window.localStorage.setItem("[Experiences]AllExperiences", JSON.stringify(experiences));